name: Release
on:
  push:
    tags:
      - v**.**.**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - working-directory: sample-app
        run: make test
      - working-directory: sample-app
        run: make build
      - uses: actions/upload-artifact@v4
        with:
          name: sample-app-artifact
          path: sample-app/sample-app-binary
  release:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: sample-app-artifact
      - run: gh release create $GITHUB_REF_NAME sample-app-binary --generate-notes --verify-tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
