name: Test and build
on:
  workflow_call:
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: golang:1.22
    steps:
      - uses: actions/checkout@v4
      - working-directory: sample-app
        run: make test
  build:
    runs-on: ubuntu-latest
    container:
      image: golang:1.22
    needs: [test]
    steps:
      - uses: actions/checkout@v4
      - working-directory: sample-app
        run: make build
      - uses: actions/upload-artifact@v4
        with:
          name: sample-app-artifact
          path: sample-app/sample-app-binary
