name: Run on push
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - working-directory: sample-app
        run: make test
      - working-directory: sample-app
        run: make build
