name: Release
on:
  push:
    tags:
      - v**.**.**
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - working-directory: sample-app
        run: make test
      - working-directory: sample-app
        run: make build
      - run: gh release create $GITHUB_REF_NAME sample-app/sample-app-binary --generate-notes --verify-tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
